name: iPilates
favicon: null
layout_spectrum: 0.5937351994216442
typography_spectrum: 0.16839079069904983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.06804480985738337
  lightness: 0.7884341939352453
  saturation: 0.2607123111374676
  rhythmicContrast: 0.8483124058693647
purpose: []
