analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2607123111374676
  brandStrength: 0.1027569
  lightness: 0.7884341939352453
  brandColors:
    - '#F2F2F2'
    - '#030303'
    - '#909090'
    - '#404040'
    - '#6C6C6C'
  rhythmicContrast: 0.8483124058693647
typography_spectrum: 0.5037594
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2005012
favicon: null
name: iPilates
